export const text = {
  heroTitle: '지도 하나로 완성하는 K‑콘텐츠 성지순례',
  heroSub: '좋아하는 드라마·뮤비 촬영지를 한눈에 보고, 저장하고, 코스를 공유하세요.',
  Browse: '여행시작하기',
  Map: '지도열기',
  dramaTrending: '요즘 인기: 오징어 게임, 이태원 클라쓰',
  kpopTrending: '요즘 인기: BTS, 뉴진스',
  movieTrending: '요즘 인기: 케이팝데몬헌터스',
  popularNow: '지금 인기',
  seeAll: '전체 보기',
  mapSectionTitle: '스팟 보기',
  mapPreviewTitle: '스팟 미리보기',
  sampleSpotName: 'Dalgona Game – Hongdae Shop',
  sampleSpotMeta: 'Ep.3 • 12:30 • Seoul Mapo‑gu',
  openFullMap: '전체 지도 열기',
  selectedSpotTitle: '선택된 스팟',
  save: '저장',
  directions: '경로 보기',
  popularRoutesTitle: '인기 코스',
  share: '공유',
  spots: '스팟',
};
