apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kspot-nextjs-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "kspot-static-ip"
    networking.gke.io/managed-certificates: "kspot-ssl-cert"
    kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
  - host: kspot.site
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: kspot-nextjs-service
            port:
              number: 80
  - host: www.kspot.site
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: kspot-nextjs-service
            port:
              number: 80