apiVersion: v1
kind: Service
metadata:
  name: kspot-nextjs-service
  labels:
    app: kspot-nextjs
spec:
  type: LoadBalancer  # GKE에서 외부 IP를 자동으로 할당
  selector:
    app: kspot-nextjs
  ports:
  - protocol: TCP
    port: 80        # 외부에서 접근할 포트
    targetPort: 3000  # 컨테이너 포트
  sessionAffinity: ClientIP  # 세션 유지를 위한 설정 (선택사항)
