apiVersion: v1
kind: Service
metadata:
  name: kspot-nextjs-service
  labels:
    app: kspot-nextjs
    environment: production
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort  
  selector:
    app: kspot-nextjs
  ports:
  - protocol: TCP
    port: 80       
    targetPort: 3000  
  sessionAffinity: ClientIP 
