/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as VerifiedEmailRouteImport } from './pages/verified-email'
import { Route as MapRouteImport } from './pages/map'
import { Route as IndexRouteImport } from './pages/index'
import { Route as VerifiedEmailVerifyEmailRouteImport } from './pages/verified-email/verify-email'
import { Route as LocationIdRouteImport } from './pages/location.$id'
import { Route as ContentIdRouteImport } from './pages/content.$id'
import { Route as AuthSignupSuccessRouteImport } from './pages/auth/signup-success'
import { Route as AuthSignupRouteImport } from './pages/auth/signup'
import { Route as AuthResetPasswordRouteImport } from './pages/auth/reset-password'
import { Route as AuthLoginRouteImport } from './pages/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './pages/auth/forgot-password'
import { Route as ContentContentIdMapRouteImport } from './pages/content.$contentId.map'

const VerifiedEmailRoute = VerifiedEmailRouteImport.update({
  id: '/verified-email',
  path: '/verified-email',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifiedEmailVerifyEmailRoute =
  VerifiedEmailVerifyEmailRouteImport.update({
    id: '/verify-email',
    path: '/verify-email',
    getParentRoute: () => VerifiedEmailRoute,
  } as any)
const LocationIdRoute = LocationIdRouteImport.update({
  id: '/location/$id',
  path: '/location/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentIdRoute = ContentIdRouteImport.update({
  id: '/content/$id',
  path: '/content/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupSuccessRoute = AuthSignupSuccessRouteImport.update({
  id: '/auth/signup-success',
  path: '/auth/signup-success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentContentIdMapRoute = ContentContentIdMapRouteImport.update({
  id: '/content/$contentId/map',
  path: '/content/$contentId/map',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/verified-email': typeof VerifiedEmailRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/signup-success': typeof AuthSignupSuccessRoute
  '/content/$id': typeof ContentIdRoute
  '/location/$id': typeof LocationIdRoute
  '/verified-email/verify-email': typeof VerifiedEmailVerifyEmailRoute
  '/content/$contentId/map': typeof ContentContentIdMapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/verified-email': typeof VerifiedEmailRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/signup-success': typeof AuthSignupSuccessRoute
  '/content/$id': typeof ContentIdRoute
  '/location/$id': typeof LocationIdRoute
  '/verified-email/verify-email': typeof VerifiedEmailVerifyEmailRoute
  '/content/$contentId/map': typeof ContentContentIdMapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/verified-email': typeof VerifiedEmailRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/signup-success': typeof AuthSignupSuccessRoute
  '/content/$id': typeof ContentIdRoute
  '/location/$id': typeof LocationIdRoute
  '/verified-email/verify-email': typeof VerifiedEmailVerifyEmailRoute
  '/content/$contentId/map': typeof ContentContentIdMapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/map'
    | '/verified-email'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/signup-success'
    | '/content/$id'
    | '/location/$id'
    | '/verified-email/verify-email'
    | '/content/$contentId/map'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/map'
    | '/verified-email'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/signup-success'
    | '/content/$id'
    | '/location/$id'
    | '/verified-email/verify-email'
    | '/content/$contentId/map'
  id:
    | '__root__'
    | '/'
    | '/map'
    | '/verified-email'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/signup-success'
    | '/content/$id'
    | '/location/$id'
    | '/verified-email/verify-email'
    | '/content/$contentId/map'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapRoute: typeof MapRoute
  VerifiedEmailRoute: typeof VerifiedEmailRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthSignupSuccessRoute: typeof AuthSignupSuccessRoute
  ContentIdRoute: typeof ContentIdRoute
  LocationIdRoute: typeof LocationIdRoute
  ContentContentIdMapRoute: typeof ContentContentIdMapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verified-email': {
      id: '/verified-email'
      path: '/verified-email'
      fullPath: '/verified-email'
      preLoaderRoute: typeof VerifiedEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verified-email/verify-email': {
      id: '/verified-email/verify-email'
      path: '/verify-email'
      fullPath: '/verified-email/verify-email'
      preLoaderRoute: typeof VerifiedEmailVerifyEmailRouteImport
      parentRoute: typeof VerifiedEmailRoute
    }
    '/location/$id': {
      id: '/location/$id'
      path: '/location/$id'
      fullPath: '/location/$id'
      preLoaderRoute: typeof LocationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/$id': {
      id: '/content/$id'
      path: '/content/$id'
      fullPath: '/content/$id'
      preLoaderRoute: typeof ContentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup-success': {
      id: '/auth/signup-success'
      path: '/auth/signup-success'
      fullPath: '/auth/signup-success'
      preLoaderRoute: typeof AuthSignupSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/$contentId/map': {
      id: '/content/$contentId/map'
      path: '/content/$contentId/map'
      fullPath: '/content/$contentId/map'
      preLoaderRoute: typeof ContentContentIdMapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface VerifiedEmailRouteChildren {
  VerifiedEmailVerifyEmailRoute: typeof VerifiedEmailVerifyEmailRoute
}

const VerifiedEmailRouteChildren: VerifiedEmailRouteChildren = {
  VerifiedEmailVerifyEmailRoute: VerifiedEmailVerifyEmailRoute,
}

const VerifiedEmailRouteWithChildren = VerifiedEmailRoute._addFileChildren(
  VerifiedEmailRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapRoute: MapRoute,
  VerifiedEmailRoute: VerifiedEmailRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthSignupSuccessRoute: AuthSignupSuccessRoute,
  ContentIdRoute: ContentIdRoute,
  LocationIdRoute: LocationIdRoute,
  ContentContentIdMapRoute: ContentContentIdMapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
